className: func.myFunc
tenant: public
namespace: default
name: myFunc
inputs:
- persistent://public/default/sensors
output: persistent://public/default/sensors-filtered
broker-service-url pulsar://ec2-18-223-193-14.us-east-2.compute.amazonaws.com:6650

##################################
# Processing 
##################################
autoAck: true
logTopic: persistent://public/default/sensors-log
processingGuarantees: ATLEAST_ONCE
retainOrdering: true
timeoutMs: 30000
subName: sensors-sub
cleanupSubscription: true
